version: "3.4"
services:
  couchdb:
    image: arsnova/arsnova-couchdb:2.6
    build: ./arsnova-couchdb
    ports:
      - "5984:5984"
    volumes:
      - "data:/usr/local/var/lib/couchdb"
  webapp:
    image: arsnova/arsnova-webapp:2.6
    build: ./arsnova-webapp
    ports:
      - "8080:8080"
      - "8090:8090"
    links:
      - couchdb
    env_file: webapp.env
  nginx:
    image: arsnova/arsnova-nginx:2.6
    build: ./arsnova-nginx
    ports:
      - "80:80"
    links:
      - webapp
volumes:
  data:
    name: arsnova_data
